Numpy::

--> NumPy stand as Numerical Python
--> NumPy is a Python library used for working with arrays.
--> NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
--> NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
--> The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
--> NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [3]:
import numpy as np

# Define two matrices using NumPy arrays
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Matrix multiplication using NumPy's dot function
result = np.dot(A, B)

# Display the result
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
3


In [2]:
import numpy as np
print(np.__version__)

1.24.2


In [3]:
import numpy as np

In [4]:
a=np.array(10)
print(a)

10


In [5]:
## one dimension
a=np.array([10,20,30])    ## Array is space separated values ## list is comma separated value
print(a)

[10 20 30]


In [6]:
# 2-dimension
a=np.array([[10,35],[67,98]])
print(a)

[[10 35]
 [67 98]]


In [7]:
a[1][0]

67

In [8]:
# 3 dimension
## collection of 2-D is ntg but 3 dimensional 
a=np.array([[[1,2],[4,5]],[[6,8],[7,8]]])   ## 3 suubscripts 
print(a)

[[[1 2]
  [4 5]]

 [[6 8]
  [7 8]]]


In [9]:
a[0][1][0]

4

In [10]:
a=[1,2,3]
b=np.asarray(a,dtype=float)
print(b)

[1. 2. 3.]


In [11]:
a=[[10,20],[30,40]]
b=np.asarray(a,order="C")
print(b)

[[10 20]
 [30 40]]


In [12]:
for i in np.nditer(b):  
    print(i)

10
20
30
40


In [17]:
a=b"Welocome to my world"
np.frombuffer(a,dtype="S1",count=2,offset=9)

array([b't', b'o'], dtype='|S1')

In [ ]:
a=[2,3,4,5]

In [18]:
np.fromiter(a,dtype="S1",count=3)  ## dtype is function  

array([b'8', b'1', b'1'], dtype='|S1')

In [20]:
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [23]:
a=np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
a=np.zeros([2,3,3])
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [25]:
a=np.full([2,3],1)  ## 2,3 array with 1
print(a)

[[1 1 1]
 [1 1 1]]


In [26]:
np.random.rand(2,3)   ## direct paranthesis ## only zero to 1

array([[0.80919187, 0.73158353, 0.1292264 ],
       [0.49778419, 0.94772798, 0.40776067]])

In [27]:
np.ones([1,2])

array([[1., 1.]])

In [28]:
np.eye(3)   ## diagonal elements with one remaining zero

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
a=np.arange(10,20,1)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [31]:
np.arange(0,100,20,dtype=float)

array([ 0., 20., 40., 60., 80.])

In [35]:
a=np.arange(1,7,1)

In [36]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)   ## without endpoint it o/p 11 values by default endpoint True # retstep 

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)

In [41]:
np.linspace(0,100,20,endpoint=False,retstep=True)

(array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
        65., 70., 75., 80., 85., 90., 95.]),
 5.0)

In [42]:
np.logspace(1,10,10,base=2)  ## default base value 10

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [43]:
## Array Properties
a=np.arange(10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
a.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [45]:
a=a.reshape(3,3)  ##updation

In [46]:
np.size(a)

9

In [47]:
np.shape(a)

(3, 3)

In [48]:
a.dtype

dtype('int32')

In [49]:
b=np.array([10,20,30],dtype=float)
b

array([10., 20., 30.])

In [50]:
b.dtype

dtype('float64')

In [52]:
##  Array Operations
a=np.array([[10,20,30],[40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
a[0]

array([10, 20, 30])

In [54]:
a[0][1]

20

In [55]:
s=np.arange(10,100,10)
print(s)

[10 20 30 40 50 60 70 80 90]


In [56]:
s[2:5]

array([30, 40, 50])

In [57]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [59]:
b=np.copy(a)
b

array([[10, 20, 30],
       [40, 50, 60]])

In [60]:
c=b.view()
c

array([[10, 20, 30],
       [40, 50, 60]])

In [61]:
print(a)
print(b)
print(c)

[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]


In [62]:
a[0][1]=200

In [63]:
a

array([[ 10, 200,  30],
       [ 40,  50,  60]])

In [67]:
b[0][2]=300
b

array([[ 10,  20, 300],
       [ 40,  50,  60]])

In [68]:
c

array([[ 10,  20, 300],
       [ 40,  50,  60]])

In [69]:
a=np.array([30,293,93,93,8,23])
a=np.sort(a)
a

array([  8,  23,  30,  93,  93, 293])

In [70]:
a=a.reshape(2,3)
a

array([[  8,  23,  30],
       [ 93,  93, 293]])

In [72]:
np.sort(a,axis=0)  

array([[  8,  23,  30],
       [ 93,  93, 293]])

## 0-D Arrays::
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.


In [43]:
arr =np.array(42)
print(arr)

42


## 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [1]:
import numpy as np
## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])     
print(arr1)
print(type(arr1))
print(arr1.shape)    ## sinlge dimensional array with 5 elements

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [15]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)      ## 1 row and 5 columns
print(type(arr2))

##arr2.reshape(1,4) , ValueError: cannot reshape array of size 5 into shape (1,4)


<class 'numpy.ndarray'>


## 2-D
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [13]:
## 2-D Array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [6 7 8 9 0]]


(2, 5)

## 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [46]:
arr=np.array([[[1,2,3],[4,5,6]] , [[2,3,4],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [4 5 6]]]


## ndim
NumPy Arrays provides the ""ndim"" attribute that returns an integer that tells us how many dimensions the array have.

In [47]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Shape of an Array:: The shape of an array is the number of elements in each dimension.

## Reshaping arrays:
--> Reshaping means changing the shape of an array.
--> The shape of an array is the number of elements in each dimension.
--> By reshaping we can add or remove dimensions or change number of elements in each dimension.


In [62]:
#Reshape From 1-D to 2-D
arr=np.array([1,2,3,4,5,6]).reshape(2,3)
print("Two Dimensional Array is: ",arr)
print()

Two Dimensional Array is:  [[1 2 3]
 [4 5 6]]



In [65]:
#Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Can We Reshape Into any Shape?
--> Yes, as long as the elements required for reshaping are equal in both shapes.

In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [28]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
## Attributes of Numpy Array
arr=np.array([[1,2,3],[4,5,6]])
print("Array :",arr)
print("shape :",arr.shape)       ##output: (2,3)
print("No of dimensions:",arr.ndim)        ##output: 2
print("Size:",arr.size)        ##output:6
print("Data Type:",arr.dtype)       ##output: int32
print("Item size:",arr.itemsize)    ##output: 8

Array : [[1 2 3]
 [4 5 6]]
shape : (2, 3)
No of dimensions: 2
Size: 6
Data Type: int32
Item size: 4


In [17]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element Wise addition
print("Addition:",arr1+arr2)

## Element wise substraction
print("Substraction: ",arr1-arr2)

## Element Wise Multiplication
print("Multiplication:",arr1*arr2)

## Element wise substraction
print("Divison: ",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Divison:  [0.1 0.1 0.1 0.1 0.1]


In [18]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))
## Exponential
print(np.exp(arr))
## Sine
print(np.sin(arr))
## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
## array slicing and Indexing

arr=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print("Array:\n",arr)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
#arr[0][0]
arr[0]

array([1, 2, 3, 4])

In [28]:
#arr[0][1]
print(arr[1:])
arr[1:,2:]

[[ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 7,  8],
       [11, 12]])

In [30]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [32]:
## Modify array elements
arr[0,2]=300
print(arr)

[[  1   2 300   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [33]:
arr[1:]=400
print(arr)

[[  1   2 300   4]
 [400 400 400 400]
 [400 400 400 400]]


In [35]:
## Statistical concepts -- Normalization
## to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev=np.std(data)

## Normalize the data
normalized_data=(data-mean)/std_dev
print("Normalized data:",normalized_data)






Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [37]:
data =np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:",mean)

#Median
median =np.median(data)
print("Median:",median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance=np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [41]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
#data[data>5]
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

## NumPy Array Copy vs View
--> The main difference between a copy and a view of an array is 
The copy is a new array and the view is just a view of the original array.

--> The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

--> The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## Copy
The copy SHOULD NOT be affected by the changes made to the original array.

In [48]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


## View
The view SHOULD be affected by the changes made to the original array.

In [50]:
#Make a view, change the original array, and display both arrays
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [52]:
## Make Changes in the VIEW
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


## copies owns the data, and views does not own the data
--> The copy returns None.
--> The view returns the original array.

In [53]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Returns Copy or View
--> returns the original array, so it is a view.

In [66]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)  #Output::[1 2 3 4 5 6 7 8] --> View 

[1 2 3 4 5 6 7 8]


## Flattening the arrays --> syntax:: reshape(-1)
Flattening array means converting a multidimensional array into a 1D array.

In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
